version: '2'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: dev_jenkins
    ports:
      - "8080:8080"
    environment:
      VIRTUAL_HOST: "jenkins.vm"
      VIRTUAL_PORT: "8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        ipv4_address: 172.18.0.200

networks:
  default:
    external:
      name: dev
